SELECT CITY, length(CITY)
FROM STATION
WHERE CITY IN
((SELECT CITY FROM STATION
  WHERE length(CITY)=(SELECT length(CITY) FROM STATION ORDER BY length(CITY) LIMIT 1)
  ORDER BY CITY
  LIMIT 1),
  (SELECT CITY FROM STATION
  WHERE length(CITY)=(SELECT length(CITY) FROM STATION ORDER BY length(CITY) DESC LIMIT 1)
  ORDER BY CITY
  LIMIT 1));
